google:
  credentials_path: '~/dev/football/credentials'
  spreadsheet_id: '1jlDdFE1zlYOVb535x15QVmEAlxB0rQYM6ARjY8vaQ3w'
games:
  year: 2022
  url:
    bowls: 'http://www.espn.com/college-football/scoreboard/_/group/80/year/{year}/seasontype/3/week/1'
    inseason: 'http://www.espn.com/college-football/scoreboard/_/group/80/year/{year}/seasontype/2/week/{week}'
output: '~/dev/football/game_lists'
player_list: [
  'Hoke',
  'Lou',
  'Tom',
  'Paul',
  'Brian',
  'Alex',
  'Scott',
  'Chris',
  'Sean',
  'Mike',
  'Tarik',
  'Cyrus'
  ]
