Air Force Falcons:
  Abbreviation: AF
  Mascot: Falcons
Akron Zips:
  Abbreviation: AKR
  Mascot: Zips
Alabama Crimson Tide:
  Abbreviation: BAMA
  Mascot: Crimson Tide
Appalachian State Mountaineers:
  Abbreviation: APP ST
  Mascot: Mountaineers
Arizona State Sun Devils:
  Abbreviation: ASU
  Mascot: Sun Devils
Arizona Wildcats:
  Abbreviation: ZONA
  Mascot: Wildcats
Arkansas Razorbacks:
  Abbreviation: ARK
  Mascot: Razorbacks
Arkansas State Red Wolves:
  Abbreviation: ARKst
  Mascot: Red Wolves
Army Black Knights:
  Abbreviation: Army
  Mascot: Black Knights
Auburn Tigers:
  Abbreviation: AUB
  Mascot: Tigers
BYU Cougars:
  Abbreviation: BYU
  Mascot: Cougars
Ball State Cardinals:
  Abbreviation: BSU
  Mascot: Cardinals
Baylor Bears:
  Abbreviation: BAY
  Mascot: Bears
Boise State Broncos:
  Abbreviation: BOISE
  Mascot: Broncos
Boston College Eagles:
  Abbreviation: BC
  Mascot: Eagles
Bowling Green Falcons:
  Abbreviation: BGSU
  Mascot: Falcons
Buffalo Bulls:
  Abbreviation: BUFF
  Mascot: Bulls
California Golden Bears:
  Abbreviation: CAL
  Mascot: Golden Bears
Central Michigan Chippewas:
  Abbreviation: CMU
  Mascot: Chips
Charlotte 49ers:
  Abbreviation: CHAR
  Mascot: 49ers
Cincinnati Bearcats:
  Abbreviation: UC
  Mascot: Bearcats
Clemson Tigers:
  Abbreviation: CLEM
  Mascot: Tigers
Coastal Carolina Chanticleers:
  Abbreviation: CCU
  Mascot: Chanticleers
Colorado Buffaloes:
  Abbreviation: COLO
  Mascot: Primes
Colorado State Rams:
  Abbreviation: CSU
  Mascot: Rams
Duke Blue Devils:
  Abbreviation: DUKE
  Mascot: Blue Devils
East Carolina Pirates:
  Abbreviation: ECU
  Mascot: Pirates
Eastern Michigan Eagles:
  Abbreviation: EMU
  Mascot: Eagles
Florida Atlantic Owls:
  Abbreviation: FAU
  Mascot: Owls
Florida Gators:
  Abbreviation: UF
  Mascot: Gators
Florida International Panthers:
  Abbreviation: FIU
  Mascot: Panthers
Florida State Seminoles:
  Abbreviation: FSU
  Mascot: Seminoles
Fresno State Bulldogs:
  Abbreviation: FRES
  Mascot: Bulldogs
Georgia Bulldogs:
  Abbreviation: UGA
  Mascot: Dawgs
Georgia Southern Eagles:
  Abbreviation: GSO
  Mascot: Eagles
Georgia State Panthers:
  Abbreviation: GSU
  Mascot: Panthers
Georgia Tech Yellow Jackets:
  Abbreviation: GT
  Mascot: Wreck
Hawaii Rainbow Warriors:
  Abbreviation: HAW
  Mascot: Rainbow Warriors
Houston Cougars:
  Abbreviation: UH
  Mascot: Cougars
Illinois Fighting Illini:
  Abbreviation: ILL
  Mascot: Illini
Indiana Hoosiers:
  Abbreviation: IU
  Mascot: Hoosiers
Iowa Hawkeyes:
  Abbreviation: IOWA
  Mascot: Hawkeyes
Iowa State Cyclones:
  Abbreviation: ISU
  Mascot: Cyclones
Jacksonville State Gamecocks:
  Abbreviation: JVILLE
  Mascot: Gamecocks
James Madison Dukes:
  Abbreviation: JMU
  Mascot: Dukes
Kansas Jayhawks:
  Abbreviation: KAN
  Mascot: Jayhawks
Kansas State Wildcats:
  Abbreviation: KSU
  Mascot: Wildcats
Kent State Golden Flashes:
  Abbreviation: KENT
  Mascot: Golden Flashes
Kentucky Wildcats:
  Abbreviation: UK
  Mascot: Wildcats
LSU Tigers:
  Abbreviation: LSU
  Mascot: Tigahs
Liberty Flames:
  Abbreviation: LIB
  Mascot: Flames
Louisiana Ragin Cajuns:
  Abbreviation: LOU
  Mascot: Ragin Cajuns
Louisiana Tech Bulldogs:
  Abbreviation: LT
  Mascot: Bulldogs
Louisville Cardinals:
  Abbreviation: LVILLE
  Mascot: Cards
Marshall Thundering Herd:
  Abbreviation: MAR
  Mascot: Herd
Maryland Terrapins:
  Abbreviation: UMD
  Mascot: Terrapins
Memphis Tigers:
  Abbreviation: MEM
  Mascot: Tigers
Miami (OH) RedHawks:
  Abbreviation: MIAMI
  Mascot: Redhawks
Miami Hurricanes:
  Abbreviation: MIAMI(FL)
  Mascot: Canes
Michigan State Spartans:
  Abbreviation: MSU
  Mascot: Sparty
Michigan Wolverines:
  Abbreviation: MICH
  Mascot: Woverines
Middle Tennessee Blue Raiders:
  Abbreviation: MTSU
  Mascot: Blue Raiders
Minnesota Golden Gophers:
  Abbreviation: MINN
  Mascot: Gophers
Mississippi State Bulldogs:
  Abbreviation: MSSU
  Mascot: Bulldogs
Missouri Tigers:
  Abbreviation: MIZZ
  Mascot: Tigers
NC State Wolfpack:
  Abbreviation: NC ST
  Mascot: WolfPack
Navy Midshipmen:
  Abbreviation: NAVY
  Mascot: Midshipmen
Nebraska Cornhuskers:
  Abbreviation: NEB
  Mascot: Cornhuskers
Nevada Wolf Pack:
  Abbreviation: NEV
  Mascot: Wolf Pack
New Mexico Lobos:
  Abbreviation: UNM
  Mascot: Lobos
New Mexico State Aggies:
  Abbreviation: NMSU
  Mascot: Aggies
North Carolina Tar Heels:
  Abbreviation: UNC
  Mascot: Tar Heels
North Texas Mean Green:
  Abbreviation: UNT
  Mascot: Mean Green
Northern Illinois Huskies:
  Abbreviation: NIU
  Mascot: Huskies
Northwestern Wildcats:
  Abbreviation: NU
  Mascot: Wildcats
Notre Dame Fighting Irish:
  Abbreviation: ND
  Mascot: Irish
Ohio Bobcats:
  Abbreviation: OHIO
  Mascot: Bobcats
Ohio State Buckeyes:
  Abbreviation: tOSU
  Mascot: Buckeyes
Oklahoma Sooners:
  Abbreviation: OU
  Mascot: Sooners
Oklahoma State Cowboys:
  Abbreviation: OK ST
  Mascot: Cowboys
Old Dominion Monarchs:
  Abbreviation: ODU
  Mascot: Monarchs
Ole Miss Rebels:
  Abbreviation: Ole Miss
  Mascot: Traitors
Oregon Ducks:
  Abbreviation: ORE
  Mascot: Ducks
Oregon State Beavers:
  Abbreviation: OSU
  Mascot: Beavers
Penn State Nittany Lions:
  Abbreviation: PSU
  Mascot: Nittany Lions
Pittsburgh Panthers:
  Abbreviation: PITT
  Mascot: Panthers
Purdue Boilermakers:
  Abbreviation: Purdue
  Mascot: Boilermakers
Rice Owls:
  Abbreviation: Rice
  Mascot: Owls
Rutgers Scarlet Knights:
  Abbreviation: RUT
  Mascot: Scarlet Knights
SMU Mustangs:
  Abbreviation: SMU
  Mascot: Mustags
Sam Houston State Bearkats:
  Abbreviation: SHSU
  Mascot: Bearkats
San Diego State Aztecs:
  Abbreviation: SDSU
  Mascot: Aztecs
San Jose State Spartans:
  Abbreviation: SJSU
  Mascot: Spartans
South Alabama Jaguars:
  Abbreviation: USA
  Mascot: Jaguars
South Carolina Gamecocks:
  Abbreviation: SCAR
  Mascot: Gamecocks
South Florida Bulls:
  Abbreviation: SFLA
  Mascot: Bulls
Southern Mississippi Golden Eagles:
  Abbreviation: SMU
  Mascot: Golden Eagles
Stanford Cardinal:
  Abbreviation: STAN
  Mascot: Cardinal
Syracuse Orange:
  Abbreviation: SYR
  Mascot: Orange
TCU Horned Frogs:
  Abbreviation: TCU
  Mascot: Horned Frogs
Temple Owls:
  Abbreviation: TEM
  Mascot: Owls
Tennessee Volunteers:
  Abbreviation: TENN
  Mascot: Vols
Texas A&M Aggies:
  Abbreviation: TAMU
  Mascot: Aggies
Texas Longhorns:
  Abbreviation: TEX
  Mascot: Longhorns
Texas State Bobcats:
  Abbreviation: TSU
  Mascot: Bobcats
Texas Tech Red Raiders:
  Abbreviation: TTU
  Mascot: Red Raiders
Toledo Rockets:
  Abbreviation: UT
  Mascot: Rockets
Troy Trojans:
  Abbreviation: TROY
  Mascot: Trojans
Tulane Green Wave:
  Abbreviation: TU
  Mascot: Green Wave
Tulsa Golden Hurricane:
  Abbreviation: TUL
  Mascot: Golden Hurricanes
UAB Blazers:
  Abbreviation: UAB
  Mascot: Blazers
UCF Knights:
  Abbreviation: UCF
  Mascot: Knights
UCLA Bruins:
  Abbreviation: UCLA
  Mascot: Bruins
UConn Huskies:
  Abbreviation: UCONN
  Mascot: Huskies
UL Monroe Warhawks:
  Abbreviation: MONROE
  Mascot: Warhawks
UMass Minutemen:
  Abbreviation: UMASS
  Mascot: Minutemen
UNLV Rebels:
  Abbreviation: UNLV
  Mascot: Rebels
USC Trojans:
  Abbreviation: USC
  Mascot: Trojans
UTEP Miners:
  Abbreviation: UTEP
  Mascot: Miners
UTSA Roadrunners:
  Abbreviation: UTSA
  Mascot: Roadrunners
Utah State Aggies:
  Abbreviation: USU
  Mascot: Aggies
Utah Utes:
  Abbreviation: UTAH
  Mascot: Utes
Vanderbilt Commodores:
  Abbreviation: VANDY
  Mascot: Dores
Virginia Cavaliers:
  Abbreviation: UVA
  Mascot: Cavs
Virginia Tech Hokies:
  Abbreviation: VT
  Mascot: Hokies
Wake Forest Demon Deacons:
  Abbreviation: WF
  Mascot: Deacs
Washington Huskies:
  Abbreviation: UW
  Mascot: Huskies
Washington State Cougars:
  Abbreviation: WSU
  Mascot: Cougs
West Virginia Mountaineers:
  Abbreviation: WVU
  Mascot: Mtneers
Western Kentucky Hilltoppers:
  Abbreviation: WKU
  Mascot: Hilltoppers
Western Michigan Broncos:
  Abbreviation: WMU
  Mascot: Broncos
Wisconsin Badgers:
  Abbreviation: WISC
  Mascot: Badgers
Wyoming Cowboys:
  Abbreviation: WYO
  Mascot: Cowboys
